### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by ManojPrabhakar** [princeton-nlp/PURE#20]
Hi,
I am getting the below error while running the evaluation run_entity.py for SciERC. Did you come across this error before?

    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by hihihihiwsf** [comment]
> I had PyTorch compatibility issues with my GPU A100. Now it has been resolved by updating the version using pip.

Hi, can you install all the dependencies on A100 successfully? I am using A5000, but installing allennlp==0.9.0 need a very low torch version, which is not compatible with a higher version GPU. Can you share all the package versions you have installed?
