### ISSUE TITLE
CUDA error when trying to run command

### ISSUE THREAD

**Issue by AlanQuille** [princeton-nlp/PURE#32]
Hi, I tried to run the commands for the pre-trained model:

python run_entity.py \
    --do_eval --eval_test \
    --context_window 0 \
    --task scierc \
    --data_dir ${scierc_dataset} \
    --model allenai/scibert_scivocab_uncased \
    --output_dir ${scierc_ent_model}

and the custom model:

python run_entity.py --do_train --learning_rate=1e-5 --task_learning_rate=5e-4 --train_batch_size=16 --context_window 0 --data_dir data_dir --model bert-base-uncased --output_dir output_dir --task inception

I get this error for both:

![image](https://user-images.githubusercontent.com/33432976/134182567-d2180fa1-b603-43c1-92af-7a1182406f64.png)

Here are my specs:

RTX 3060 , CUDA 11.2
torch==1.4.0

Do you think it is the Nvidia version that is causing the issue? Thank you very much.

**Comment by AlanQuille** [comment]
Hi, the issue is resolved. I upgraded to pytorch version 1.9.0 (cu11) and my custom model is working. Thanks again for all your help.
